wandb_version: 1

learning_rate:
  desc: null
  value: 0.0006
hidden_layers:
  desc: null
  value: 15
hidden_layer_size:
  desc: null
  value: 436
batch_size:
  desc: null
  value: 32
timestamps:
  desc: null
  value: 5
architecture:
  desc: null
  value: RNN
gru_layers:
  desc: null
  value: 7
_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.17.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1725261064
    t:
      1:
      - 1
      - 5
      - 30
      - 53
      - 55
      2:
      - 1
      - 5
      - 30
      - 53
      - 55
      3:
      - 1
      - 13
      - 16
      - 23
      4: 3.10.14
      5: 0.17.6
      8:
      - 5
      13: linux-x86_64
