STATE:
  - VX
  - VY
  - YAW_RATE
  - THROTTLE_FB
  - STEERING_FB
ACTIONS:
  - THROTTLE_CMD
  - STEERING_CMD
PARAMETERS:
  - Bf: 
  - Cf: 
  - Df: 
  - Ef:
  - Br: 
  - Cr: 
  - Dr: 
  - Er:
  - Cm1: 
  - Cr0: 
  - Cr2: 
  - Iz: 
  - mass:
  - Ffz:
  - Frz:
VEHICLE_SPECS:
  lf: 1.890
  lr: 2.610
MODEL:
  NAME: DeepDynamicsIAC
  HORIZON: 7
  LAYERS:
    - GRU:
      OUT_FEATURES: 49
      LAYERS: 2
    - DENSE:
      OUT_FEATURES: 105
      ACTIVATION: Mish
    - DENSE:
      OUT_FEATURES: 105
      ACTIVATION: Mish
    - DENSE:
      OUT_FEATURES: 105
      ACTIVATION: Mish
    - DENSE:
      ACTIVATION: Softplus
  OPTIMIZATION:
    LOSS: MSE
    BATCH_SIZE: 4
    NUM_EPOCHS: 400
    OPTIMIZER: Adam
    LR: 0.0002
    WEIGHT_DECAY: 0.00001
