STATE:
  - VX
  - VY
  - YAW_RATE
  - THROTTLE_FB
  - STEERING_FB
ACTIONS:
  - THROTTLE_CMD
  - STEERING_CMD
PARAMETERS:
  - Bf: 2.579
  - Cf: 1.2
  - Df: 0.192
  - Br: 3.3852
  - Cr: 1.2691
  - Dr: 0.1737
  - Cm1: 0.287
  - Cm2: 0.0545
  - Cr0: 0.0518
  - Cr2: 0.00035
  - Izz: 27.8e-6
VEHICLE_SPECS:
  lf: 0.029
  lr: 0.033
  mass: 0.041
MODEL:
  NAME: DeepDynamics
  HORIZON: 2
  LAYERS:
    # - GRU:
    #   OUT_FEATURES: 4
    #   LAYERS: 1
    - DENSE:
      OUT_FEATURES: 32
      ACTIVATION: Mish
    - DENSE:
      OUT_FEATURES: 32
      ACTIVATION: Mish
    # - DENSE:
    #   OUT_FEATURES: 32
    #   ACTIVATION: Mish
    - DENSE:
      ACTIVATION: Softplus
  OPTIMIZATION:
    LOSS: MAE
    BATCH_SIZE: 4
    NUM_EPOCHS: 400
    OPTIMIZER: Adam
    LR: 0.0002
