STATE:
  - VX
  - VY
  - YAW_RATE
  - THROTTLE_FB
  - STEERING_FB
ACTIONS:
  - THROTTLE_CMD
  - STEERING_CMD
PARAMETERS:
  - Bf: 
  - Cf: 
  - Df: 
  - Br: 
  - Cr: 
  - Dr: 
  - Cm1: 
  - Cm2: 
  - Cr0: 
  - Cr2: 
  - Iz: 
VEHICLE_SPECS:
  lf: 1.248
  lr: 1.7328
  mass: 790.0
MODEL:
  NAME: DeepDynamics
  HORIZON: 1
  LAYERS:
    # - GRU:
    #   OUT_FEATURES: 196
    #   LAYERS: 3
    # - DENSE:
    #   OUT_FEATURES: 51
    #   ACTIVATION: Mish
    #   OUT_FEATURES: 51
    #   ACTIVATION: Mish
    # - DENSE:
    #   OUT_FEATURES: 51
    #   ACTIVATION: Mish
    - DENSE:
      ACTIVATION: Softplus
  OPTIMIZATION:
    LOSS: MSE
    BATCH_SIZE: 64
    NUM_EPOCHS: 400
    OPTIMIZER: Adam
    LR: 0.2
