STATE:
  - VX
  - VY
  - YAW_RATE
  - THROTTLE_FB
  - STEERING_FB
ACTIONS:
  - THROTTLE_CMD
  - STEERING_CMD
PARAMETERS: 
  - B:
    Min: 1.0
    Max: 20.0
  - C:
    Min: 1.0
    Max: 2.0
  - D:
    Min: 100.0
    Max: 5000.0
  - Iz: 
    Min: 1500.0
    Max: 3500.0

VEHICLE_SPECS:
  lf: 1.088 
  lr: 1.632 
  mass: 1350 
MODEL:
  NAME: DeepDynamicsCN7
  HORIZON: 15
  LAYERS:
    - GRU:
      OUT_FEATURES: 225
      LAYERS: 3
    - DENSE:
      OUT_FEATURES: 226
      ACTIVATION: Mish
    - DENSE:
      OUT_FEATURES: 226
      ACTIVATION: Mish
    - DENSE:
      OUT_FEATURES: 226
      ACTIVATION: Mish
    - DENSE:
      OUT_FEATURES: 226
      ACTIVATION: Mish
    - DENSE:
      OUT_FEATURES: 226
      ACTIVATION: Mish
    - DENSE:
      OUT_FEATURES: 226
      ACTIVATION: Mish
  OPTIMIZATION:
    LOSS: MSE
    BATCH_SIZE: 128
    NUM_EPOCHS: 300
    OPTIMIZER: Adam
    LR: 0.001124514638266798
  # HORIZON: 20
  # LAYERS:
  #   - GRU:
  #     OUT_FEATURES: 400
  #     LAYERS: 2
  #   - DENSE:
  #     OUT_FEATURES: 246
  #     ACTIVATION: Mish
  #   - DENSE:
  #     OUT_FEATURES: 246
  #     ACTIVATION: Mish
  #   - DENSE:
  #     OUT_FEATURES: 246
  #     ACTIVATION: Mish
  #   - DENSE:
  #     OUT_FEATURES: 246
  #     ACTIVATION: Mish
  #   - DENSE:
  #     OUT_FEATURES: 246
  #     ACTIVATION: Mish
  #   - DENSE:
  #     OUT_FEATURES: 246
  #     ACTIVATION: Mish
  # OPTIMIZATION:
  #   LOSS: MSE
  #   BATCH_SIZE: 64
  #   NUM_EPOCHS: 300
  #   OPTIMIZER: Adam
  #   LR: 0.0005348228056950509
