STATE:
  - VX
  - VY
  - YAW_RATE
  - THROTTLE_FB
  - STEERING_FB
ACTIONS:
  - THROTTLE_CMD
  - STEERING_CMD
PARAMETERS:
  - Bf: 
  - Cf: 
  - Df: 
  - Br: 
  - Cr: 
  - Dr: 
  - Frx:
VEHICLE_SPECS:
  lf: 1.248
  lr: 1.7328
  mass: 790.0
  Iz: 1000.0
MODEL:
  NAME: DeepPacejka
  HORIZON: 9
  LAYERS:
    - GRU:
      OUT_FEATURES: 81
      LAYERS: 8
    - DENSE:
      OUT_FEATURES: 175
      ACTIVATION: Mish
    - DENSE:
      OUT_FEATURES: 175 
      ACTIVATION: Mish
    - DENSE:
      ACTIVATION: Softplus
  OPTIMIZATION:
    LOSS: MSE
    BATCH_SIZE: 4
    NUM_EPOCHS: 400
    OPTIMIZER: Adam
    LR: 0.1
