STATE:
  - VX
  - VY
  - YAW_RATE
  - THROTTLE_FB
  - STEERING_FB
ACTIONS:
  - THROTTLE_CMD
  - STEERING_CMD
PARAMETERS:
  - Bf:
    Min: 1.0
    Max: 3.0
  - Cf:
    Min: 1.2
    Max: 1.6
  - Df:
    Min: 25.0
    Max: 40.0
  - Br:
    Min: 1.0
    Max: 3.0
  - Cr:
    Min: 1.2
    Max: 1.6
  - Dr:
    Min: 25.0
    Max: 40.0
  - Cm0:
    Min: 0.039
    Max: 0.041
  - Iz: 
    Min: 0.07
    Max: 0.11
  
VEHICLE_SPECS:
  lf: 0.175
  lr: 0.15
  mass: 3.5
MODEL:
  NAME: DeepDynamicsF1T
  HORIZON: 15
  LAYERS:
    - GRU:
      OUT_FEATURES: 225
      LAYERS: 1
    - DENSE:
      OUT_FEATURES: 256
      ACTIVATION: Mish
    - DENSE:
      OUT_FEATURES: 256
      ACTIVATION: Mish

  OPTIMIZATION:
    LOSS: MSE
    BATCH_SIZE: 128
    NUM_EPOCHS: 400
    OPTIMIZER: Adam
    LR: 0.005
