STATE:
  - VX
  - VY
  - YAW_RATE
  - THROTTLE_FB
  - STEERING_FB
ACTIONS:
  - THROTTLE_CMD
  - STEERING_CMD
PARAMETERS:
  # - Bf:
  #   Min: 9.0
  #   Max: 12.0
  # - Cf:
  #   Min: 1.0
  #   Max: 1.5
  # - Df:
  #   Min: 1000.0
  #   Max: 5000.0
  # - Br:
  #   Min: 9.0
  #   Max: 12.0
  # - Cr:
  #   Min: 1.0
  #   Max: 1.5
  # - Dr:
  #   Min: 1000.0
  #   Max: 5000.0
  # - Cm1:
  #   Min: 0.0
  #   Max: 2.0  
  - B:
    Min: 0.0
    Max: 0.5
  - C:
    Min: 0.0
    Max: 2.0
  - D:
    Min: 0.0
    Max: 5000.0
  - Iz: 
    Min: 2000.0
    Max: 5000.0

VEHICLE_SPECS:
  lf: 1.86 
  lr: 2.79 
  mass: 1350 
MODEL:
  NAME: DeepDynamicsCN7
  HORIZON: 15
  LAYERS:
    - GRU:
      OUT_FEATURES: 225
      LAYERS: 3
    - DENSE:
      OUT_FEATURES: 188
      ACTIVATION: Mish
    - DENSE:
      OUT_FEATURES: 188
      ACTIVATION: Mish
  OPTIMIZATION:
    LOSS: MSE
    BATCH_SIZE: 128
    NUM_EPOCHS: 800
    OPTIMIZER: Adam
    LR: 0.001
