STATE:
  - VX
  - VY
  - YAW_RATE
  - STEERING_FB
ACTIONS:
  - STEERING_CMD
  - VREF
PARAMETERS:
  - Bf: 
  - Cf: 
  - Df: 
  - Ef:
  - Br: 
  - Cr: 
  - Dr:
  - Er:
  - Svf:
  - Shf:
  - Svr:
  - Shr:
  - Frx:
VEHICLE_SPECS:
  lf: 1.248
  lr: 1.7328
  mass: 790.0
  Iz: 1000.0
MODEL:
  NAME: DeepPacejkaIAC
  HORIZON: 13
  LAYERS:
    - GRU:
      OUT_FEATURES: 169
      LAYERS: 4
    - DENSE:
      OUT_FEATURES: 406
      ACTIVATION: Mish
    - DENSE:
      OUT_FEATURES: 406
      ACTIVATION: Mish
  OPTIMIZATION:
    LOSS: MSE
    BATCH_SIZE: 128
    NUM_EPOCHS: 400
    OPTIMIZER: Adam
    LR: 0.000598
