STATE:
  - VX
  - VY
  - YAW_RATE
  - THROTTLE_FB
  - STEERING_FB
ACTIONS:
  - THROTTLE_CMD
  - STEERING_CMD
PARAMETERS:
  - Bf:
    Min: 5.0
    Max: 30.0
  - Cf:
    Min: 0.5
    Max: 2.0
  - Df:
    Min: 100.0
    Max: 10000.0
  - Ef:
    Min: -2.0
    Max: 0.0
  - Br:
    Min: 5.0
    Max: 30.0
  - Cr:
    Min: 0.5
    Max: 2.0
  - Dr:
    Min: 100.0
    Max: 10000.0
  - Er:
    Min: -2.0
    Max: 0.0
  - Cm1:
    Min: 0.0
    Max: 1000.0  
  - Cm2:
    Min: 0.0
    Max: 1.0
  - Cr0:
    Min: 0.348
    Max: 1.392
  - Cr2:
    Min: 0.179
    Max: 0.718
  - Iz: 
    Min: 500.0
    Max: 2000.0
VEHICLE_SPECS:
  lf: 1.248
  lr: 1.7328
  mass: 790.0
MODEL:
<<<<<<< HEAD
  NAME: DeepDynamicsIAC
  HORIZON: 5
=======
  NAME: DeepDynamics
  HORIZON: 15
>>>>>>> ac62f5fa07a379c3d0d421cdae44cbac8ef8e9ce
  LAYERS:
    - GRU:
      OUT_FEATURES: 225
      LAYERS: 15
    - DENSE:
      OUT_FEATURES: 258
      ACTIVATION: Mish
    - DENSE:
      OUT_FEATURES: 258
      ACTIVATION: Mish
    - DENSE:
      OUT_FEATURES: 258
      ACTIVATION: Mish
    - DENSE:
      OUT_FEATURES: 258
      ACTIVATION: Mish
    - DENSE:
      OUT_FEATURES: 258
      ACTIVATION: Mish
    - DENSE:
      OUT_FEATURES: 258
      ACTIVATION: Mish
    - DENSE:
      OUT_FEATURES: 258
      ACTIVATION: Mish
    - DENSE:
      OUT_FEATURES: 258
      ACTIVATION: Mish
    - DENSE:
      OUT_FEATURES: 258
      ACTIVATION: Mish
    - DENSE:
      OUT_FEATURES: 258
      ACTIVATION: Mish
    - DENSE:
      OUT_FEATURES: 258
      ACTIVATION: Mish
  OPTIMIZATION:
    LOSS: MSE
    BATCH_SIZE: 4
    NUM_EPOCHS: 400
    OPTIMIZER: Adam
    LR: 0.0006
