STATE:
  - VX
  - VY
  - YAW_RATE
  - THROTTLE_FB
  - STEERING_FB
ACTIONS:
  - THROTTLE_CMD
  - STEERING_CMD
PARAMETERS:
  - Bf: 2.579
    Min: 1.290
    Max: 5.158
  - Cf: 1.2
    Min: 0.6
    Max: 2.4
  - Df: 0.192
    Min: 0.096
    Max: 0.384
  - Ef: 0.0
    Min: -2.0
    Max: 0.0
  - Br: 3.3852
    Min: 1.6926
    Max: 6.7704
  - Cr: 1.2691
    Min: 0.6345
    Max: 2.5380
  - Dr: 0.1737
    Min: 0.0869
    Max: 0.3474
  - Er: 0.0
    Min: -2.0
    Max: 0.0
  - Cm1: 0.287
    Min: 0.1435
    Max: 0.574
  - Cm2: 0.0545
    Min: 0.02725
    Max: 0.109
  - Cr0: 0.0518
    Min: 0.0259
    Max: 0.1036
  - Cr2: 0.00035
    Min: 1.75e-4
    Max: 7.0e-4
  - Iz: 27.8e-6
    Min: 1.39e-5
    Max: 5.56e-5
VEHICLE_SPECS:
  lf: 0.029
  lr: 0.033
  mass: 0.041
MODEL:
  NAME: DeepDynamics
  HORIZON: 4
  LAYERS:
    - GRU:
      OUT_FEATURES: 16
      LAYERS: 8
    - DENSE:
      OUT_FEATURES: 299
      ACTIVATION: Mish
    - DENSE:
      OUT_FEATURES: 299
      ACTIVATION: Mish
    - DENSE:
      OUT_FEATURES: 299
      ACTIVATION: Mish
    - DENSE:
      OUT_FEATURES: 299
      ACTIVATION: Mish
    - DENSE:
      OUT_FEATURES: 299
      ACTIVATION: Mish
    - DENSE:
      OUT_FEATURES: 299
      ACTIVATION: Mish
  OPTIMIZATION:
    LOSS: MSE
    BATCH_SIZE: 32
    NUM_EPOCHS: 400
    OPTIMIZER: Adam
    LR: 0.001
