STATE:
  - VX
  - VY
  - YAW_RATE
  - THROTTLE_FB
  - STEERING_FB
ACTIONS:
  - THROTTLE_CMD
  - STEERING_CMD
PARAMETERS:
  - Bf: 2.579
    Min: 1.0
    Max: 12.0
  - Cf: 1.2
    Min: 1.0
    Max: 2.0
  - Df: 0.192
    Min: 0.1
    Max: 1.9
  - Br: 3.3852
    Min: 1.0
    Max: 12.0
  - Cr: 1.2691
    Min: 1.0
    Max: 2.0
  - Dr: 0.1737
    Min: 0.1
    Max: 0.9
  - Cm1: 0.287
  - Cm2: 0.0545
  - Cr0: 0.0518
  - Cr2: 0.00035
  - Iz: 27.8e-6
VEHICLE_SPECS:
  lf: 0.029
  lr: 0.033
  mass: 0.041
MODEL:
  NAME: DeepDynamics
  HORIZON: 8
  LAYERS:
    - GRU:
      OUT_FEATURES: 64
      LAYERS: 16
    - DENSE:
      OUT_FEATURES: 469
      ACTIVATION: Mish
    - DENSE:
      OUT_FEATURES: 469
      ACTIVATION: Mish
    - DENSE:
      OUT_FEATURES: 469
      ACTIVATION: Mish
    - DENSE:
      OUT_FEATURES: 469
      ACTIVATION: Mish
    - DENSE:
      OUT_FEATURES: 469
      ACTIVATION: Mish
    - DENSE:
      OUT_FEATURES: 469
      ACTIVATION: Mish
    - DENSE:
      OUT_FEATURES: 469
      ACTIVATION: Mish
    - DENSE:
      OUT_FEATURES: 469
      ACTIVATION: Mish
    - DENSE:
      OUT_FEATURES: 469
      ACTIVATION: Mish
    - DENSE:
      OUT_FEATURES: 469
      ACTIVATION: Mish
    - DENSE:
      OUT_FEATURES: 469
      ACTIVATION: Mish
    - DENSE:
      OUT_FEATURES: 469
      ACTIVATION: Mish
    - DENSE:
      OUT_FEATURES: 469
      ACTIVATION: Mish
  OPTIMIZATION:
    LOSS: MSE
    BATCH_SIZE: 8
    NUM_EPOCHS: 400
    OPTIMIZER: Adam
    LR: 0.001
