STATE:
  - V
  - SLIP_ANGLE
  - YAW_RATE
  - THROTTLE_FB
  - STEERING_FB
ACTIONS:
  - THROTTLE_CMD
  - STEERING_CMD
PARAMETERS: 
  - Bf:
    Min: 0.9
    Max: 2.0
  - Cf:
    Min: 1.499
    Max: 1.5
  - Df:
    Min: 20.0
    Max: 60.0
  - Br:
    Min: 0.9
    Max: 2.0
  - Cr:
    Min: 1.499
    Max: 1.5
  - Dr:
    Min: 20.0
    Max: 60.0
  - Cm0:
    Min: 0.0399
    Max: 0.0400
  - Iz: 
    Min: 0.09
    Max: 0.3

VEHICLE_SPECS:
  lf: 0.175 
  lr: 0.15 
  mass: 3.5
MODEL:
  NAME: SlipF1T
  HORIZON: 20
  LAYERS:
    - GRU:
      OUT_FEATURES: 400
      LAYERS: 2
    - DENSE:
      OUT_FEATURES: 74
      ACTIVATION: Mish
    - DENSE:
      OUT_FEATURES: 74
      ACTIVATION: Mish

  OPTIMIZATION:
    LOSS: MAE
    BATCH_SIZE: 64
    NUM_EPOCHS: 300
    OPTIMIZER: Adam
    LR: 0.002

